[env]
TERM = "xterm-256color"

[font]
normal = { family = "Input Mono", style = "Medium" }
bold = { family = "Input Mono", style = "Medium" }
italic = { family = "Input Mono", style = "Italic" }
size = 16

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 8, y = 8 }
dynamic_padding = true
decorations = "None"
startup_mode = "Maximized"
opacity = 1.0

[cursor]
style = { shape = "Beam", blinking = "always" }
blink_interval = 512
blink_timeout = 0

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[general]
import = ["~/.dotfiles/alacritty/themes/nvim.toml",]
